name       : python-show-in-file-manager
version    : 1.1.1
release    : 1
source     :
    - https://github.com/damonlynch/showinfilemanager/archive/refs/tags/v1.1.1.tar.gz : 6acf03149a50626d0c5387f2bd75f61b05db4698a331908527c90a105178d0fc
homepage   : https://github.com/damonlynch/showinfilemanager
license    : MIT
component  : programming.python
summary    : Python module to open the system file manager and select files in it
description: |
    Show in File Manager is a Python package to open the system file manager and optionally select files in it. The point is not to open the files, but to select them in the file manager, thereby highlighting the files and allowing the user to quickly do something with them.
rundeps    :
    - python-packaging
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
